Create lib-openblas-0.2.20-universal package
ctuning/ck-math pull request #15
Opened 2017-09-06 10:23 UTC by dsavenko

Hi,

This PR covers https://github.com/ctuning/ck-math/issues/10 .

I tested the build on various systems, seems to work fine.

2017-09-06 11:06 UTC, psyhtest commented on package/lib-openblas-0.2.20-universal/README.txt
> +$ ck install package:lib-openblas-0.2.19-universal --env.OPENBLAS_TARGET=ARMV7 --env.OPENBLAS_FORTRAN=YES --env.OPENBLAS_LAPACK=YES
0.2.20

2017-09-06 11:13 UTC, psyhtest requested changes
1) Please exclude the directory package/lib-openblas-0.2.20-universal/arc from this commit.

2) Please use in headers:

See CK LICENSE.txt for licensing details.
See CK COPYRIGHT.txt for copyright details.

3) Please README.txt to README.md and update 0.2.19 to 0.2.20.

2017-09-06 14:18 UTC, psyhtest commented
@dsavenko Sorry for the niggles. Just better to clean up now than again see them when copying `lib-openblas-0.2.20-universal` to ` lib-openblas-0.2.21-universal`, etc.

2017-09-07 04:35 UTC, dsavenko commented
@psyhtest, done 1 and 3. I didn't get what you mean by 2. Those lines are already present in `info.json` and all the scripts.

2017-09-07 09:33 UTC, psyhtest commented
>  I didn't get what you mean by 2. 
Just uniform capitalisations and file extensions everywhere e.g. `COPYRIGHT.txt` instead of `Copyright`.

2017-09-07 09:34 UTC, psyhtest approved these changes

2017-09-07 09:44 UTC, merged

2017-09-07 09:44 UTC, dsavenko commented
Fixed capitalization and merged.